[tool.poetry]
name = "ragify-engine"
version = "0.1.0"
description = ""
authors = ["Vishal <vishal@bluebash.co>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
tika = "^2.6.0"
xgboost = "2.1.0"
torch = "2.3.1"
pdfplumber = "0.11.2"
pypdf2 = "3.0.1"
cachetools = "5.4.0"
ruamel-yaml = "0.18.6"
aspose-slides = "24.7.0"
strenum = "0.4.15"
huggingface-hub = "0.24.0"
pdfminer-six = "20231228"
six = "1.16.0"
opencv-python = "4.10.0.84"
onnxruntime = "1.18.1"
shapely = "2.0.5"
pyclipper = "1.3.0.post5"
tiktoken = "0.7.0"
datrie = "0.8.2"
hanziconv = "0.3.2"
nltk = "3.8.1"
roman-numbers = "1.0.2"
word2number = "1.1"
cn2an = "0.5.22"
readability-lxml = "0.8.1"
lxml = "^5.2.2"
lxml-html-clean = "0.1.1"
html-text = "0.6.2"
python-docx = "1.1.0"
pandas = "2.2.2"
openpyxl = "3.1.5"
python-pptx = "0.6.23"
markdown = "3.6"
xpinyin = "0.7.6"
umap-learn = "^0.5.6"
langchain-openai = "0.1.17"
python-dotenv = "1.0.1"
langchain-postgres = "0.0.9"
flagembedding = "^1.2.10"
langchain-google-genai = "^1.0.8"
cohere = "^5.6.2"
langchain-community = "^0.2.11"
pypdf = "^4.3.1"
pycryptodomex = "^3.20.0"
elasticsearch = "^8.15.0"
elasticsearch-dsl = "^8.15.1"
werkzeug = "^3.0.4"
flask = "^3.0.3"
peewee = "^3.17.6"
flask-cors = "^4.0.1"
flask-login = "^0.6.3"
flask-session = "^0.8.0"
pymysql = "^1.1.1"
zhipuai = "^2.1.4.20230814"
ollama = "^0.3.2"
dashscope = "^1.20.5"
volcengine = "^1.0.150"
groq = "^0.10.0"
minio = "^7.2.8"
peft = "^0.12.0"
html2text = "^2024.2.26"
ormsgpack = "^1.5.0"
markdown-to-json = "^2.1.1"
redis = "^5.0.8"
demjson3 = "^3.0.6"
selenium = "^4.24.0"
webdriver-manager = "^4.0.2"
duckduckgo-search = "^6.2.11"
wikipedia = "^1.4.0"
bio = "^1.7.1"
arxiv = "^2.1.3"
serpapi = "^0.1.5"
google-search-results = "^2.4.2"
scholarly = "^1.7.11"
deepl = "^1.18.0"
graspologic = "^3.4.1"
future = "^1.0.0"
editdistance = "^0.8.1"


[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
