ragflow:
  host: 0.0.0.0
  http_port: 9380
mysql:
  name: 'rag_flow'
  user: 'root'
  password: 'infini_rag_flow'
  host: 'mysql'
  port: 3306
  max_connections: 100
  stale_timeout: 30
minio:
  user: 'rag_flow'
  password: 'infini_rag_flow'
  host: 'minio:9000'
es:
  #hosts: 'http://es01:9200'
  hosts: 'http://localhost:1200'
  username: 'elastic'
  password: 'infini_rag_flow'
redis:
  db: 1
  #password: 'infini_rag_flow'
  #host: '172.17.0.1:6379'
  host: 'localhost:6379'
AMS:
  AMS_ENDPOINT: 'https://api-appstag.kickcall.ai'
  #AMS_ENDPOINT: 'https://api-app.kickcall.ai'
  AMS_AUTHORIZATION_KEY: 'b46adfec15fd5f8c758f81118e1d031486c5cc34aee394caa116e4b50580ee3eb3a925fd05da8dc2c2afe201cbd21908d5af7227f78d796c5bccc30e9e7c1f9b'

ENV:
  name: 'stage'
  length_url_to_scrape: 5